[package]
name = "http_server"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [
    "rest_service/router_layer_response",
     "tracing/axum_minimal_tracing"
]

[workspace.dependencies]
axum = { version = "0.8.4", workspace = true } 
tokio = { version = "1.47.1", features = ["full"], workspace = true }
