[package]
name = "config_http"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
axum = { workspace = true }
config = "0.15.15"
dotenvy = "0.15.7"
reqwest = { version = "0.12.23", features = ["json"] }
tokio = { workspace = true}
