[package]
name = "ws_json"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true, features = ["ws"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
